PORTNAME=	qdeliver
DISTVERSION=	g20200926
CATEGORIES=	mail

MAINTAINER=	dl-ports@perfec.to
COMMENT=	Define Qmail delivery instructions in webdav
LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		go:modules
USE_GITHUB=	yes
GH_ACCOUNT=	wavemechanics
GH_PROJECT=	qdeliver
GH_TAGNAME=	e3da7ce

# Generated by gomod-vendor
GH_TUPLE=	golang:net:ab3426394381:golang_net/vendor/golang.org/x/net \
		wavemechanics:etype:v0.0.1:wavemechanics_etype/vendor/github.com/wavemechanics/etype

GO_TARGET=	./cmd/qdeliver

PORTEXAMPLES=	qdeliver-handler.sh qdeliver-notify.sh

do-install:
	${INSTALL_PROGRAM} ${GO_WRKDIR_BIN}/qdeliver ${STAGEDIR}${PREFIX}/libexec/
	${MKDIR} ${STAGEDIR}${EXAMPLESDIR}
	cd ${WRKSRC}/scripts && ${INSTALL_DATA} ${PORTEXAMPLES} ${STAGEDIR}${EXAMPLESDIR}
	${INSTALL_MAN} ${WRKSRC}/man/qdeliver.man ${STAGEDIR}${MANPREFIX}/man/man8/qdeliver.8

.include <bsd.port.mk>
